api-keys:
  access_token = ${ACCESS_TOKEN}
  public_key = ${PUBLIC_KEY}
server:
  port: 8081

spring:
  application:
    name: api-mercado-pago
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      #em produção usar 'validate'
    database-platform: org.hibernate.dialect.PostgreSQLDialect